[package]
name = "disruption"
version = "0.1.0"
edition = "2021"
authors = ["Louis Meyer (H1ghBre4k3r) <h1ghbre4k3r@dev.bre4k3r.de>"]

[lib]
name = "disruption"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.83"
serde_repr = "0.1.9"
tokio = {version =  "1.20.1", features = ["full"] }
tokio-tungstenite = { version = "0.17.2", features = ["native-tls"] }
url = "2.2.2"
futures-util = "0.3.21"
futures-channel = "0.3"
futures = "0.3.21"
reqwest = { version = "0.11", features = ["json"] }
async-channel = "1.7.0"
env_logger = "0.9.0"
log = "0.4.17"
