[package]
name = "disruption"
version = "0.1.0"
edition = "2021"
authors = ["Louis Meyer (H1ghBre4k3r) <h1ghbre4k3r@dev.bre4k3r.de>"]

[lib]
name = "disruption"

[dependencies]
serde = { version = "1.0.168", features = ["derive"] }
serde_json = "1.0.100"
serde_repr = "0.1.14"
tokio = {version =  "1.29.1", features = ["full"] }
tokio-tungstenite = { version = "0.19.0", features = ["native-tls"] }
url = "2.4.0"
futures-util = "0.3.28"
futures-channel = "0.3"
futures = "0.3.28"
reqwest = { version = "0.11", features = ["json"] }
async-channel = "1.8.0"
env_logger = "0.10.0"
log = "0.4.19"
