[package]
name = "disruption"
version = "0.1.0"
edition = "2021"
authors = ["Louis Meyer (H1ghBre4k3r) <h1ghbre4k3r@dev.bre4k3r.de>"]
repository = "https://github.com/H1ghBre4k3r/disruption"
license = "MIT"
readme = "README.md"

[lib]
name = "disruption"

[workspace]
members = [
    "crates/*"
]

[dependencies]
disruption_types = { path = "./crates/disruption_types" }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
serde_repr = "0.1.16"
tokio = {version =  "1.32.0", features = ["full"] }
tokio-tungstenite = { version = "0.20.0", features = ["native-tls"] }
url = "2.4.0"
futures-util = "0.3.28"
futures-channel = "0.3"
futures = "0.3.28"
reqwest = { version = "0.11", features = ["json"] }
async-channel = "1.9.0"
env_logger = "0.10.0"
log = "0.4.20"
