mod activity;
mod attachment;
mod component;
mod embed;
mod interaction;
mod reaction;
mod reference;

use serde::{Deserialize, Serialize};
use serde_repr::{Deserialize_repr, Serialize_repr};

use crate::discord::entities::Application;
use crate::discord::entities::Role;
use crate::discord::entities::User;

pub use self::activity::*;
pub use self::attachment::*;
pub use self::component::*;
pub use self::embed::*;
pub use self::interaction::*;
pub use self::reaction::*;
pub use self::reference::*;

use super::ChannelMention;

/// ? https://discord.com/developers/docs/resources/channel#message-object
#[derive(Serialize, Deserialize, Debug)]
pub struct Message {
    /// id of the message
    pub id: String,
    /// id of the channel the message was sent in
    pub channel_id: String,
    /// the author of this message (not guaranteed to be a valid user, see below)
    pub author: User,
    /// contents of the message
    pub content: String,
    /// when this message was sent
    pub timestamp: String,
    /// when this message was edited (or null if never)
    pub edited_timestamp: Option<String>,
    /// whether this was a TTS message
    pub tts: bool,
    /// whether this message mentions everyone
    pub mention_everyone: bool,
    /// users specifically mentioned in the message
    pub mentions: Vec<User>,
    /// roles specifically mentioned in this message
    pub mention_roles: Vec<Role>,
    /// channels specifically mentioned in this message
    pub mention_channels: Option<Vec<ChannelMention>>,
    /// any attached files
    pub attachments: Vec<Attachment>,
    /// any embedded content
    pub embeds: Vec<Embed>,
    /// reactions to this message
    pub reactions: Option<Vec<Reaction>>,
    // TODO: integer or string?
    /// use for validatigng a message was sent
    pub nonce: Option<String>,
    /// whether this message is pinned
    pub pinned: bool,
    /// if the message is generated by a webhoo, this is the webhook's id
    pub webhook_id: Option<String>,
    /// type of the message
    #[serde(rename = "type")]
    pub type_: MessageType,
    /// send with Rich Presence-related chat embeds
    pub activity: Option<MessageActivity>,
    /// send with Rich Presence-related chat embeds
    pub application: Option<Application>,
    /// if the message is an interaction or application-owned webhoo, this is the id of the application
    pub application_id: Option<String>,
    /// data showing the source of a crosspost, channel follow add, pin, or reply message
    pub message_reference: Option<MessageReference>,
    // TODO: introduce https://discord.com/developers/docs/resources/channel#message-object-message-flags
    /// message flags combined as a bitfield
    pub flags: Option<u64>,
    /// the message associated with the message_reference
    pub referenced_message: Box<Option<Message>>,
    /// sent if the message is a response to an interaction
    pub interaction: Option<MessageInteraction>,

    // TODO: Add channel https://discord.com/developers/docs/resources/channel#channel-object
    /// the thread that was started from this message, includes thread member object
    // pub thread: Option<Channel>
    /// sent if the message contains components like buttons, action rows, orother interactive components
    pub components: Option<Vec<MessageComponent>>,
    // TODO: Add stickers https://discord.com/developers/docs/resources/sticker#sticker-item-object
    // sent if the mesasge contains stickers
    // pub sticker_items: Option<Vec<StickerItem>>,
}

/// ? https://discord.com/developers/docs/resources/channel#message-object-message-types
#[derive(Serialize_repr, Deserialize_repr, PartialEq, Debug, Default)]
#[repr(u8)]
pub enum MessageType {
    #[default]
    DEFAULT = 0,
    #[allow(non_camel_case_types)]
    RECIPIENT_ADD = 1,
    #[allow(non_camel_case_types)]
    RECIPIENT_REMOVE = 2,
    CALL = 3,
    #[allow(non_camel_case_types)]
    CHANNEL_NAME_CHANGE = 4,
    #[allow(non_camel_case_types)]
    CHANNEL_ICON_CHANGE = 5,
    #[allow(non_camel_case_types)]
    CHANNEL_PINNED_MESSAGE = 6,
    #[allow(non_camel_case_types)]
    USER_JOIN = 7,
    #[allow(non_camel_case_types)]
    GUILD_BOOST = 8,
    #[allow(non_camel_case_types)]
    GUILD_BOOST_TIER_1 = 9,
    #[allow(non_camel_case_types)]
    GUILD_BOOST_TIER_2 = 10,
    #[allow(non_camel_case_types)]
    GUILD_BOOST_TIER_3 = 11,
    #[allow(non_camel_case_types)]
    CHANNEL_FOLLOW_ADD = 12,
    #[allow(non_camel_case_types)]
    GUILD_DISCOVERY_DISQUALIFIED = 14,
    #[allow(non_camel_case_types)]
    GUILD_DISCOVERY_REQUALIFIED = 15,
    #[allow(non_camel_case_types)]
    GUILD_DISCOVERY_GRACE_PERIOD_INITIAL_WARNING = 16,
    #[allow(non_camel_case_types)]
    GUILD_DISCOVERY_GRACE_PERIOD_FINAL_WARNING = 17,
    #[allow(non_camel_case_types)]
    THREAD_CREATED = 18,
    REPLY = 19,
    #[allow(non_camel_case_types)]
    CHAT_INPUT_COMMAND = 20,
    #[allow(non_camel_case_types)]
    THREAD_STARTER_MESSAGE = 21,
    #[allow(non_camel_case_types)]
    GUILD_INVITE_REMINDER = 22,
    #[allow(non_camel_case_types)]
    CONTEXT_MENU_COMMAND = 23,
    #[allow(non_camel_case_types)]
    AUTO_MODERATION_ACTION = 24,
}
