use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write;

use serde_json::{Map, Value};

#[derive(Debug)]
pub enum CodegenError {
    Json(serde_json::Error),
    MissingSchemas,
}

impl std::fmt::Display for CodegenError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Json(error) => write!(f, "invalid OpenAPI JSON: {error}"),
            Self::MissingSchemas => write!(f, "OpenAPI document has no components.schemas object"),
        }
    }
}

impl std::error::Error for CodegenError {}

impl From<serde_json::Error> for CodegenError {
    fn from(error: serde_json::Error) -> Self {
        Self::Json(error)
    }
}

pub fn generate(document: &str) -> Result<String, CodegenError> {
    let document: Value = serde_json::from_str(document)?;
    generate_value(&document)
}

fn generate_value(document: &Value) -> Result<String, CodegenError> {
    let schemas = document
        .get("components")
        .and_then(Value::as_object)
        .and_then(|components| components.get("schemas"))
        .and_then(Value::as_object)
        .ok_or(CodegenError::MissingSchemas)?;

    let names = rust_names(schemas);
    let mut output = String::from(
        "// @generated by discord-codegen; do not edit.\n\n#![allow(clippy::all)]\n#![allow(unused_imports)]\n\nuse serde::{Deserialize, Serialize};\nuse serde_json::Value;\nuse serde_repr::{Deserialize_repr, Serialize_repr};\n\n",
    );

    for (source_name, schema) in schemas {
        emit_schema(&mut output, source_name, schema, schemas, &names);
    }

    Ok(output)
}

fn rust_names(schemas: &Map<String, Value>) -> BTreeMap<String, String> {
    let mut names = BTreeMap::new();
    let mut used = BTreeSet::new();

    for source_name in schemas.keys() {
        let base = pascal_case(source_name);
        let mut candidate = base.clone();
        let mut suffix = 2;
        while !used.insert(candidate.clone()) {
            candidate = format!("{base}{suffix}");
            suffix += 1;
        }
        names.insert(source_name.clone(), candidate);
    }

    names
}

fn emit_schema(
    output: &mut String,
    source_name: &str,
    schema: &Value,
    schemas: &Map<String, Value>,
    names: &BTreeMap<String, String>,
) {
    let rust_name = &names[source_name];

    if let Some(values) = schema.get("enum").and_then(Value::as_array) {
        emit_enum(output, rust_name, values);
        return;
    }

    if let Some(variants) = schema
        .get("oneOf")
        .or_else(|| schema.get("anyOf"))
        .and_then(Value::as_array)
    {
        if emit_union(output, rust_name, variants, names) {
            return;
        }
    }

    if schema.get("type").and_then(Value::as_str) == Some("object")
        || schema.get("properties").is_some()
        || schema.get("allOf").is_some()
    {
        emit_struct(output, rust_name, schema, schemas, names);
        return;
    }

    let type_name = type_for_schema(schema, names);
    writeln!(output, "pub type {rust_name} = {type_name};\n").unwrap();
}

fn emit_enum(output: &mut String, rust_name: &str, values: &[Value]) {
    if values.is_empty() {
        writeln!(output, "pub type {rust_name} = Value;\n").unwrap();
        return;
    }

    if values.iter().all(Value::is_string) {
        writeln!(
            output,
            "#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]"
        )
        .unwrap();
        writeln!(output, "pub enum {rust_name} {{").unwrap();

        let mut used = BTreeSet::new();
        for value in values.iter().filter_map(Value::as_str) {
            let variant = unique_name(&pascal_case(value), &mut used);
            writeln!(output, "    #[serde(rename = {value:?})]").unwrap();
            writeln!(output, "    {variant},").unwrap();
        }
        output.push_str("}\n\n");
        return;
    }

    if values.iter().all(|value| value.as_i64().is_some()) {
        writeln!(
            output,
            "#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize_repr, Deserialize_repr)]"
        )
        .unwrap();
        writeln!(output, "#[repr(i64)]").unwrap();
        writeln!(output, "pub enum {rust_name} {{").unwrap();

        let mut used = BTreeSet::new();
        for value in values.iter().filter_map(Value::as_i64) {
            let variant = unique_name(&format!("Value{value}"), &mut used);
            writeln!(output, "    {variant} = {value},").unwrap();
        }
        output.push_str("}\n\n");
        return;
    }

    writeln!(output, "pub type {rust_name} = Value;\n").unwrap();
}

fn emit_union(
    output: &mut String,
    rust_name: &str,
    variants: &[Value],
    names: &BTreeMap<String, String>,
) -> bool {
    let refs = variants
        .iter()
        .filter_map(|variant| variant.get("$ref").and_then(Value::as_str))
        .map(|reference| reference.rsplit('/').next().unwrap_or(reference))
        .collect::<Vec<_>>();

    if refs.is_empty() || refs.len() != variants.len() {
        return false;
    }

    writeln!(
        output,
        "#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]"
    )
    .unwrap();
    writeln!(output, "#[serde(untagged)]").unwrap();
    writeln!(output, "pub enum {rust_name} {{").unwrap();

    let mut used = BTreeSet::new();
    for reference in refs {
        let Some(type_name) = names.get(reference) else {
            return false;
        };
        let variant_name = unique_name(type_name, &mut used);
        writeln!(output, "    {variant_name}({type_name}),").unwrap();
    }

    output.push_str("}\n\n");
    true
}

fn emit_struct(
    output: &mut String,
    rust_name: &str,
    schema: &Value,
    schemas: &Map<String, Value>,
    names: &BTreeMap<String, String>,
) {
    let mut properties = BTreeMap::new();
    let mut required = BTreeSet::new();
    collect_object_shape(
        schema,
        schemas,
        &mut properties,
        &mut required,
        &mut BTreeSet::new(),
    );

    writeln!(
        output,
        "#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]"
    )
    .unwrap();
    writeln!(output, "pub struct {rust_name} {{").unwrap();

    let mut used = BTreeSet::new();
    for (source_name, property) in properties {
        let field_name = unique_name(&snake_case(&source_name), &mut used);
        let field_type = type_for_schema(&property, names);
        let optional = !required.contains(source_name.as_str()) || is_nullable(&property);
        let field_type = if optional {
            format!("Option<{field_type}>")
        } else {
            field_type
        };

        if field_name != source_name {
            writeln!(output, "    #[serde(rename = {source_name:?})]").unwrap();
        }
        if optional {
            output.push_str("    #[serde(default)]\n");
        }
        writeln!(output, "    pub {field_name}: {field_type},").unwrap();
    }

    output.push_str("}\n\n");
}

fn collect_object_shape(
    schema: &Value,
    schemas: &Map<String, Value>,
    properties: &mut BTreeMap<String, Value>,
    required: &mut BTreeSet<String>,
    visiting: &mut BTreeSet<String>,
) {
    if let Some(reference) = schema.get("$ref").and_then(Value::as_str) {
        let source_name = reference.rsplit('/').next().unwrap_or(reference);
        if visiting.insert(source_name.to_owned()) {
            if let Some(target) = schemas.get(source_name) {
                collect_object_shape(target, schemas, properties, required, visiting);
            }
            visiting.remove(source_name);
        }
    }

    if let Some(parts) = schema.get("allOf").and_then(Value::as_array) {
        for part in parts {
            collect_object_shape(part, schemas, properties, required, visiting);
        }
    }

    if let Some(fields) = schema.get("required").and_then(Value::as_array) {
        required.extend(fields.iter().filter_map(Value::as_str).map(str::to_owned));
    }
    if let Some(fields) = schema.get("properties").and_then(Value::as_object) {
        properties.extend(
            fields
                .iter()
                .map(|(name, schema)| (name.clone(), schema.clone())),
        );
    }
}

fn type_for_schema(schema: &Value, names: &BTreeMap<String, String>) -> String {
    if let Some(reference) = schema.get("$ref").and_then(Value::as_str) {
        let source_name = reference.rsplit('/').next().unwrap_or(reference);
        return names
            .get(source_name)
            .cloned()
            .unwrap_or_else(|| "Value".to_owned());
    }

    if let Some(types) = schema.get("type").and_then(Value::as_array) {
        if let Some(non_null) = types
            .iter()
            .filter_map(Value::as_str)
            .find(|kind| *kind != "null")
        {
            return primitive_type(non_null).to_owned();
        }
    }

    match schema.get("type").and_then(Value::as_str) {
        Some("array") => schema
            .get("items")
            .map(|items| format!("Vec<{}>", type_for_schema(items, names)))
            .unwrap_or_else(|| "Vec<Value>".to_owned()),
        Some("boolean") => "bool".to_owned(),
        Some("integer") => "i64".to_owned(),
        Some("number") => "f64".to_owned(),
        Some("string") => "String".to_owned(),
        Some("object") => "Value".to_owned(),
        _ => "Value".to_owned(),
    }
}

fn primitive_type(kind: &str) -> &'static str {
    match kind {
        "boolean" => "bool",
        "integer" => "i64",
        "number" => "f64",
        "string" => "String",
        _ => "Value",
    }
}

fn is_nullable(schema: &Value) -> bool {
    schema.get("nullable").and_then(Value::as_bool) == Some(true)
        || schema
            .get("type")
            .and_then(Value::as_array)
            .map(|types| types.iter().any(|kind| kind.as_str() == Some("null")))
            .unwrap_or(false)
}

fn unique_name(name: &str, used: &mut BTreeSet<String>) -> String {
    let base = if name.is_empty() { "Value" } else { name };
    let mut candidate = base.to_owned();
    let mut suffix = 2;
    while !used.insert(candidate.clone()) {
        candidate = format!("{base}{suffix}");
        suffix += 1;
    }
    candidate
}

fn snake_case(value: &str) -> String {
    let mut result = String::new();
    for (index, character) in value.chars().enumerate() {
        if character.is_ascii_alphanumeric() {
            if character.is_ascii_uppercase() && index > 0 {
                result.push('_');
            }
            result.push(character.to_ascii_lowercase());
        } else {
            result.push('_');
        }
    }
    if result.is_empty() {
        result.push_str("value");
    }
    if is_keyword(&result) {
        result.push('_');
    }
    if result
        .chars()
        .next()
        .is_some_and(|character| character.is_ascii_digit())
    {
        result.insert(0, '_');
    }
    result
}

fn pascal_case(value: &str) -> String {
    let mut result = String::new();
    let mut uppercase = true;
    for character in value.chars() {
        if character.is_ascii_alphanumeric() {
            if uppercase {
                result.push(character.to_ascii_uppercase());
                uppercase = false;
            } else {
                result.push(character);
            }
        } else {
            uppercase = true;
        }
    }
    if result.is_empty() {
        result.push_str("Value");
    }
    if result
        .chars()
        .next()
        .is_some_and(|character| character.is_ascii_digit())
    {
        result.insert_str(0, "Value");
    }
    result
}

fn is_keyword(value: &str) -> bool {
    matches!(
        value,
        "as" | "break"
            | "const"
            | "continue"
            | "crate"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "fn"
            | "for"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "Self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "type"
            | "unsafe"
            | "use"
            | "where"
            | "while"
            | "async"
            | "await"
            | "dyn"
    )
}

#[cfg(test)]
mod tests {
    use super::generate;

    #[test]
    fn generates_a_struct_from_a_schema() {
        let document = r##"
        {
          "openapi": "3.1.0",
          "components": {
            "schemas": {
              "User": {
                "type": "object",
                "required": ["id"],
                "properties": {
                  "id": { "type": "string" },
                  "username": { "type": "string" }
                }
              }
            }
          }
        }
        "##;

        let output = generate(document).expect("valid OpenAPI input");

        assert!(output.contains("pub struct User"));
        assert!(output.contains("pub id: String"));
        assert!(output.contains("pub username: Option<String>"));
    }

    #[test]
    fn generates_enums_unions_and_renamed_fields() {
        let document = r##"
        {
          "components": {
            "schemas": {
              "Button": {
                "type": "object",
                "properties": { "type": { "type": "string" } }
              },
              "Select": {
                "type": "object",
                "properties": { "type": { "type": "string" } }
              },
              "Component": {
                "oneOf": [
                  { "$ref": "#/components/schemas/Button" },
                  { "$ref": "#/components/schemas/Select" }
                ]
              },
              "Visibility": { "type": "string", "enum": ["public", "private"] }
            }
          }
        }
        "##;

        let output = generate(document).expect("valid OpenAPI input");

        assert!(output.contains("pub enum Component"));
        assert!(output.contains("Button(Button)"));
        assert!(output.contains("pub type_: Option<String>"));
        assert!(output.contains("pub enum Visibility"));
        assert!(output.contains("#[serde(rename = \"public\")]"));
    }

    #[test]
    fn generates_numeric_enums_and_all_of_objects() {
        let document = r##"
        {
          "components": {
            "schemas": {
              "Base": {
                "type": "object",
                "required": ["id"],
                "properties": { "id": { "type": "string" } }
              },
              "Extended": {
                "allOf": [
                  { "$ref": "#/components/schemas/Base" },
                  {
                    "type": "object",
                    "properties": { "name": { "type": "string" } }
                  }
                ]
              },
              "Priority": { "type": "integer", "enum": [1, 2] }
            }
          }
        }
        "##;

        let output = generate(document).expect("valid OpenAPI input");

        assert!(output.contains("pub struct Extended"));
        assert!(output.contains("pub id: String"));
        assert!(output.contains("pub name: Option<String>"));
        assert!(output.contains("pub enum Priority"));
        assert!(output.contains("#[repr(i64)]"));
    }
}
